config/routes.rb
SporesApp::Application.routes.draw do
  
  resources :users
  resources :sessions
  
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  match '/imprint', to: 'static#imprint'
  match '/contact', to: 'static#contact'
  

  root :to => 'static#homepage'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  attr_accessible :email, :password, :password_confirmation
  
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    find_by_email(email).try(:authenticate, password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user
  
  private
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      redirect_to new_session_url, :notice => "Error"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def homepage
  end

  def imprint
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Spores - <%= yield(:title) %></title>
		<%= stylesheet_link_tag "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<div class="container" style="margin-top: 10px;">
			<div class="navbar">
				<div class="navbar-inner">
					<%= link_to 'Spores', :root, :class => "brand" %>
				</div>
			</div>
			<% if current_user %>
				<%= current_user.email %>
				<%= link_to 'Sign out', :signout, method: "delete" %>
			<% else %>
				<%= link_to 'Sign in', :signin %>
				<%= link_to 'Sign up', :signup %>
			<% end %>
		</div>
		<div class="container">
			<%= yield %>
		</div>
	</body>
</html>

app/views/users/new.html.erb
<% provide :title, "Sign up" %>

<h1>Sign up</h1>

<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div class="error_messages">
			<h2>Form is invalid</h2>
			<ul>
				<% for message in @user.errors.full_messages %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	
	<p>
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</p>
	<p>
		<%= f.label :password %><br />
		<%= f.password_field :password %>
	</p>
	<p>
		<%= f.label :password_confirmation %><br />
		<%= f.password_field :password_confirmation %>
	</p>
	
	<p><%= f.submit %></p>
<% end %>

<p>Existing user? <%= link_to "Sign in!", signin_path %></p>